# one block plants
block.10001= oak_sapling spruce_sapling birch_sapling jungle_sapling dark_oak_sapling mangrove_propagule cherry_sapling pale_oak_sapling short_grass short_dry_grass tall_dry_grass fern bush dead_bush poppy dandelion blue_orchid allium azure_bluet oxeye_daisy cornflower lily_of_the_valley sunflower red_tulip orange_tulip white_tulip pink_tulip torchflower closed_eyeblossom open_eyeblossom wither_rose firefly_bush crimson_roots warped_roots

# two block plants
block.10002= tall_grass large_fern rose_bush sugar_cane sunflower lilac peony pitcher_plant
